name: my-ecm

services:
  db:
    extends:
      file: .docker/compose.base.yml
      service: db
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    extends:
      file: .docker/compose.base.yml
      service: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
    networks:
      - network

  apisix:
    extends:
      file: .docker/compose.base.yml
      service: apisix
    ports:
      - '${APISIX_PORT}:9080'
    volumes:
      - ${PWD}/apisix/apisix.json:/usr/local/apisix/conf/apisix.json:ro
      - ${PWD}/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    networks:
      - network

  kafka:
    extends:
      file: .docker/compose.base.yml
      service: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - network

volumes:
  kafka_data:

networks:
  network:
