// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { CategorySchema } from './src/database/entity/category.entity.js';
import { ProductSchema } from './src/database/entity/product.entity.js';
import { type Constructor, EntityManager as DriverEntityManager } from '@mikro-orm/postgresql';

export const entities = [
  CategorySchema,
  ProductSchema,
] as const;

export type Database = typeof entities;

export type EntityManager = DriverEntityManager & { '~entities': Database };
export const EntityManager = DriverEntityManager as Constructor<EntityManager>;
