// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { type Constructor, EntityManager as DriverEntityManager } from "@mikro-orm/postgresql";
import { UserSchema } from "./src/database/entity/user.entity.js";

export const entities = [UserSchema] as const;

export type Database = typeof entities;

export type EntityManager = DriverEntityManager & { "~entities": Database };
export const EntityManager = DriverEntityManager as Constructor<EntityManager>;
