services:
  node:
    container_name: node
    restart: unless-stopped
    tty: true
    working_dir: /app

  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

  caddy:
    image: caddy:2.11-alpine
    container_name: caddy
    restart: unless-stopped

  apisix:
    image: apache/apisix:3.15.0-debian
    container_name: apisix
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:8.3.2
    container_name: kafka
    restart: unless-stopped

  kafka-connect:
    build:
      context: ..
      dockerfile: .docker/kafka-connect.Dockerfile
    image: kafka-connect-debezium:1.0.0
    container_name: kafka-connect
    restart: unless-stopped

  kafka-ui:
    image: kafbat/kafka-ui:1764f6a
    container_name: kafbat-ui
    restart: unless-stopped
    depends_on:
      - kafka
